version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    links:
      - papusql
    depends_on:
      - papusql
  papusql:
    image: postgres:latest
    environment:
      POSTGRES_DB: parkings
      POSTGRES_USER: papusql
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./database/sql/parkings.sql:/docker-entrypoint-initdb.d/parkings.sql
    ports:
      - "5432:5432"
